# Generated by Django 6.1 on 2026-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_category',
            field=models.CharField(default='General', max_length=30),
        ),
    ]
